name: matrix
version: 1.3.0.9

dependencies:
  - base
  - vector
  - QuickCheck

library:
  exposed-modules: Matrix
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - QuickCheck
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - matrix
      - hspec
      - QuickCheck
